#!/bin/sh

wget -qO- http://www.columbia.edu/cu/bulletin/uwb/sel/COMS_Spring2016_text.html | grep 3101 | wc -l > svmii.txt

if [ $(cat svmii.txt) -gt 1 ]
then
    say "new section woo hoo"
fi

rm -f svmii.txt
